---
abstract: "Do not use\nC<delete> on arrays."
author:
  - 'liosha <liosha@yandex-team.ru>'
build_requires:
  Test::More: 0
  Test::Perl::Critic::Policy: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300005, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl-Critic-Policy-BuiltinFunctions-ProhibitDeleteOnArrays
requires:
  Perl::Critic::Policy: 0
  Perl::Critic::Utils: 0
  Readonly: 0
  base: 0
  perl: 5.006001
  strict: 0
  warnings: 0
version: 0.01
